name: InstantDecay
description: Leaves decay instantly
version: ${project.version}
author: Digi
main: digi.instantDecay.InstantDecay
api-version: 1.13

commands:
  instantdecay:
    description: Control command for InstantDecay
    permission: instantdecay.admin

permissions:
  instantdecay.admin:
    default: op
