name: InstantDecay
description: Leaves decay instantly
version: ${project.version}
authors: [ Jikoo, Digi ]
main: com.github.jikoo.instantdecay.InstantDecayPlugin
api-version: 1.18

commands:
  instantdecay:
    description: Control command for InstantDecay
    permission: instantdecay.admin

permissions:
  instantdecay.admin:
    default: op
